workflows:
    debug:
        name: debug android workflow
        max_build_duration: 60
        instance_type: mac_mini_m1
        environment:
            flutter: 3.22.3
            groups:
              - firebase_credentials

        scripts:
          # ANDROID APP
          - name: Build APK Debug
            script: flutter build apk --debug
          # BUILD STATUS
          - name: Build finished successfully
            script: touch ~/SUCCESS
        publishing:
          email:
            recipients:
              - rhen.noriega7@gmail.com
            notify:
              success: true
              failure: true
          firebase:
              firebase_service_account: $FIREBASE_SERVICE_TOKEN
              android:
                # Add your Android app id retrieved from Firebase console
                app_id: 1:137257188053:android:d51a6aac0b4b3587cb405c

                # Add one or more groups that you wish to distribute your Android application to.
                # You can create groups in the Firebase console
                groups: 
                  - androidTesters
                artifact_type: 'apk'